import './globals.css';
import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';
import Link from 'next/link';

const quicksand = Quicksand({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        {children}
        <div>
          <header>
            <nav>
              <ul> Logo </ul>
              <ul>
                <li>
                  <Link href="/library">Library</Link>
                </li>
                <li>
                  <Link href="/about">About</Link>
                </li>
              </ul>
            </nav>
          </header>
        </div>
      </body>
    </html>
  );
}
